{
 "title": "{TABLE_NAME}",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Bond",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dateTrunc('minute', dt) as time,\n    max(toInt32(replaceRegexpAll(replaceRegexpAll(message, '^.* bond = ([0-9,]+) \\| reward = ([0-9,]+).*$', '\\\\1'), ',', ''))) as Bond\nFROM $table\n\nWHERE message LIKE '%Thornode:Bond%'\n\nGROUP BY time\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    dateTrunc('minute', dt) as time,\n    max(toInt32(replaceRegexpAll(replaceRegexpAll(message, '^.* bond = ([0-9,]+) \\| reward = ([0-9,]+).*$', '\\\\1'), ',', ''))) as Bond\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%Thornode:Bond%'\n\nGROUP BY time\n\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Rewards",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dateTrunc('minute', dt) as time,\n    max(toInt32(replaceRegexpAll(replaceRegexpAll(message, '^.* bond = ([0-9,]+) \\| reward = ([0-9,]+).*$', '\\\\2'), ',', ''))) as Reward\nFROM $table\n\nWHERE message LIKE '%Thornode:Bond%'\n\nGROUP BY time\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    dateTrunc('minute', dt) as time,\n    max(toInt32(replaceRegexpAll(replaceRegexpAll(message, '^.* bond = ([0-9,]+) \\| reward = ([0-9,]+).*$', '\\\\2'), ',', ''))) as Reward\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%Thornode:Bond%'\n\nGROUP BY time\n\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Slash Points",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dateTrunc('minute', dt) as time,\n    max(toInt32(replaceRegexpAll(replaceRegexpAll(message, '^.* ([0-9,]+) \\| network = ([0-9,]+) \\(min\\), ([0-9,]+) \\(threshold\\), ([0-9,]+) \\(max\\).*$', '\\\\1'), ',', ''))) as \"Slash Points\"\nFROM $table\n\nWHERE message LIKE '%Thornode:SlashPoints%'\n\nGROUP BY time\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    dateTrunc('minute', dt) as time,\n    max(toInt32(replaceRegexpAll(replaceRegexpAll(message, '^.* ([0-9,]+) \\| network = ([0-9,]+) \\(min\\), ([0-9,]+) \\(threshold\\), ([0-9,]+) \\(max\\).*$', '\\\\1'), ',', ''))) as \"Slash Points\"\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%Thornode:SlashPoints%'\n\nGROUP BY time\n\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Slash Points",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dateTrunc('minute', dt) as time,\n    max(toInt32(replaceRegexpAll(replaceRegexpAll(message, '^.* ([0-9,]+) \\| network = ([0-9,]+) \\(min\\), ([0-9,]+) \\(threshold\\), ([0-9,]+) \\(max\\).*$', '\\\\2'), ',', ''))) as Min,\n    max(toInt32(replaceRegexpAll(replaceRegexpAll(message, '^.* ([0-9,]+) \\| network = ([0-9,]+) \\(min\\), ([0-9,]+) \\(threshold\\), ([0-9,]+) \\(max\\).*$', '\\\\3'), ',', ''))) as Threshold,\n    max(toInt32(replaceRegexpAll(replaceRegexpAll(message, '^.* ([0-9,]+) \\| network = ([0-9,]+) \\(min\\), ([0-9,]+) \\(threshold\\), ([0-9,]+) \\(max\\).*$', '\\\\4'), ',', ''))) as Max\nFROM $table\n\nWHERE message LIKE '%Thornode:SlashPoints%'\n\nGROUP BY time\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    dateTrunc('minute', dt) as time,\n    max(toInt32(replaceRegexpAll(replaceRegexpAll(message, '^.* ([0-9,]+) \\| network = ([0-9,]+) \\(min\\), ([0-9,]+) \\(threshold\\), ([0-9,]+) \\(max\\).*$', '\\\\2'), ',', ''))) as Min,\n    max(toInt32(replaceRegexpAll(replaceRegexpAll(message, '^.* ([0-9,]+) \\| network = ([0-9,]+) \\(min\\), ([0-9,]+) \\(threshold\\), ([0-9,]+) \\(max\\).*$', '\\\\3'), ',', ''))) as Threshold,\n    max(toInt32(replaceRegexpAll(replaceRegexpAll(message, '^.* ([0-9,]+) \\| network = ([0-9,]+) \\(min\\), ([0-9,]+) \\(threshold\\), ([0-9,]+) \\(max\\).*$', '\\\\4'), ',', ''))) as Max\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%Thornode:SlashPoints%'\n\nGROUP BY time\n\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dateTrunc('minute', dt) as time,\n    replaceRegexpAll(message, '^Kubernetes:([a-zA-Z]+):Pod:Restarts: ([0-9]+)$', '\\\\1') as node,\n    sum(toInt32(replaceRegexpAll(message, '^Kubernetes:([a-zA-Z]+):Pod:Restarts: ([0-9]+)$', '\\\\2'))) as restarts\nFROM $table\n\nWHERE message LIKE '%Pod:Restarts%'\n\nGROUP BY\n    time,\n    node\nORDER BY time\n",
     "rawQuery": "SELECT\n    dateTrunc('minute', dt) as time,\n    replaceRegexpAll(message, '^Kubernetes:([a-zA-Z]+):Pod:Restarts: ([0-9]+)$', '\\\\1') as node,\n    sum(toInt32(replaceRegexpAll(message, '^Kubernetes:([a-zA-Z]+):Pod:Restarts: ([0-9]+)$', '\\\\2'))) as restarts\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%Pod:Restarts%'\n\nGROUP BY\n    time,\n    node\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dateTrunc('hour', dt) as time,\n    replaceRegexpAll(message, '^Kubernetes:([a-zA-Z]+):Pod:DiskUsage: [0-9.,]+[a-zA-Z]+ \\/ [0-9.,]+[a-zA-Z]+ \\(([0-9.]+)%\\)$', '\\\\1') as node,\n    max(round(toFloat32(replaceRegexpAll(message, '^Kubernetes:([a-zA-Z]+):Pod:DiskUsage: [0-9.,]+[a-zA-Z]+ \\/ [0-9.,]+[a-zA-Z]+ \\(([0-9.]+)%\\)$', '\\\\2')))) as diskUsage\nFROM $table\n\nWHERE message LIKE '%Pod:DiskUsage%'\n\nGROUP BY\n    time,\n    node\nORDER BY time\n",
     "rawQuery": "SELECT\n    dateTrunc('hour', dt) as time,\n    replaceRegexpAll(message, '^Kubernetes:([a-zA-Z]+):Pod:DiskUsage: [0-9.,]+[a-zA-Z]+ \\/ [0-9.,]+[a-zA-Z]+ \\(([0-9.]+)%\\)$', '\\\\1') as node,\n    max(round(toFloat32(replaceRegexpAll(message, '^Kubernetes:([a-zA-Z]+):Pod:DiskUsage: [0-9.,]+[a-zA-Z]+ \\/ [0-9.,]+[a-zA-Z]+ \\(([0-9.]+)%\\)$', '\\\\2')))) as diskUsage\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%Pod:DiskUsage%'\n\nGROUP BY\n    time,\n    node\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dateTrunc('minute', dt) as time,\n    replaceRegexpAll(message, '^Loki:([a-zA-Z-]+):.*$', '\\\\1') as node,\n    count(node) as count\nFROM $table\n\nWHERE\n    message LIKE 'Loki:%:%'\n    AND level = 'error'\nGROUP BY\n    time,\n    node\nORDER BY time\n",
     "rawQuery": "SELECT\n    dateTrunc('minute', dt) as time,\n    replaceRegexpAll(message, '^Loki:([a-zA-Z-]+):.*$', '\\\\1') as node,\n    count(node) as count\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE\n    message LIKE 'Loki:%:%'\n    AND level = 'error'\nGROUP BY\n    time,\n    node\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Warn Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dateTrunc('minute', dt) as time,\n    replaceRegexpAll(message, '^Loki:([a-zA-Z-]+):.*$', '\\\\1') as node,\n    count(node) as count\nFROM $table\n\nWHERE\n    message LIKE 'Loki:%:%'\n    AND level = 'warn'\nGROUP BY\n    time,\n    node\nORDER BY time\n",
     "rawQuery": "SELECT\n    dateTrunc('minute', dt) as time,\n    replaceRegexpAll(message, '^Loki:([a-zA-Z-]+):.*$', '\\\\1') as node,\n    count(node) as count\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE\n    message LIKE 'Loki:%:%'\n    AND level = 'warn'\nGROUP BY\n    time,\n    node\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Info Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dateTrunc('minute', dt) as time,\n    replaceRegexpAll(message, '^Loki:([a-zA-Z-]+):.*$', '\\\\1') as node,\n    count(node) as count\nFROM $table\n\nWHERE\n    message LIKE 'Loki:%:%'\n    AND level = 'info'\nGROUP BY\n    time,\n    node\nORDER BY time\n",
     "rawQuery": "SELECT\n    dateTrunc('minute', dt) as time,\n    replaceRegexpAll(message, '^Loki:([a-zA-Z-]+):.*$', '\\\\1') as node,\n    count(node) as count\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE\n    message LIKE 'Loki:%:%'\n    AND level = 'info'\nGROUP BY\n    time,\n    node\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Blocks Ahead / Behind",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "WITH blockHeights as (\n  SELECT\n    dateTrunc('minute', dt) as time,\n    replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\1'), ',', '') as node,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as nodeBlockHeight,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\3'), ',', '')) as apiBlockHeight\n  \n  FROM $table\n  \n  WHERE message LIKE '%:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n)\n\nSELECT\n  time,\n  node,\n  max(nodeBlockHeight - apiBlockHeight) as diff\n\nFROM blockHeights\n\nGROUP BY\n  time,\n  node\n\nORDER BY time",
     "rawQuery": "WITH blockHeights as (\n  SELECT\n    dateTrunc('minute', dt) as time,\n    replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\1'), ',', '') as node,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as nodeBlockHeight,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\3'), ',', '')) as apiBlockHeight\n  \n  FROM {DATABASE_NAME}.{TABLE_NAME}\n  \n  WHERE message LIKE '%:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n)\n\nSELECT\n  time,\n  node,\n  max(nodeBlockHeight - apiBlockHeight) as diff\n\nFROM blockHeights\n\nGROUP BY\n  time,\n  node\n\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "THORChain Height",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM $table\n\nWHERE message LIKE '%Thorchain:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%Thorchain:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Binance Height",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM $table\n\nWHERE message LIKE '%Binance:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%Binance:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Bitcoin Height",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM $table\n\nWHERE message LIKE '%Bitcoin:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%Bitcoin:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Ethereum Height",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM $table\n\nWHERE message LIKE '%Ethereum:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%Ethereum:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Litecoin Height",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM $table\n\nWHERE message LIKE '%Litecoin:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%Litecoin:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "BitcoinCash Height",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM $table\n\nWHERE message LIKE '%BitcoinCash:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%BitcoinCash:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Dogecoin Height",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM $table\n\nWHERE message LIKE '%Dogecoin:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%Dogecoin:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Cosmos Height",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM $table\n\nWHERE message LIKE '%Cosmos:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%Cosmos:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  },
  {
   "title": "Avalanche Height",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "{DATABASE_NAME}",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM $table\n\nWHERE message LIKE '%Avalanche:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time\n",
     "rawQuery": "SELECT\n    dt as time,\n    toInt32(replaceRegexpAll(replaceRegexpAll(message, '^([a-zA-Z]+):isSynced: nodeBlockHeight = ([0-9,]+) \\| apiBlockHeight = ([0-9,]+)$', '\\\\2'), ',', '')) as blockHeight\nFROM {DATABASE_NAME}.{TABLE_NAME}\n\nWHERE message LIKE '%Avalanche:isSynced: nodeBlockHeight = % | apiBlockHeight = %'\n\nORDER BY time",
     "round": "0s",
     "table": "{TABLE_NAME}"
    }
   ]
  }
 ]
}